### ISSUE TITLE
Run as nonRoot user

### ISSUE THREAD

**Issue by SandraGarciaSerrano** [lightdash/helm-charts#39]
The deployment fails with `Error: EACCES: permission denied, mkdir 'logs'` after adding 
```
podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
```
Which is needed since the container runs as non-root user and the image runs as root. There should be a way to run the image as non root user.
