### ISSUE TITLE
podAnnotations incorrectly indented in deployment templates

### ISSUE THREAD

**Issue by CharlieDixon** [lightdash/helm-charts#79]
Pod annotations are incorrectly indented in the `backendDeployment.yaml` and `workerDeployment.yaml`, resulting in incorrectly rendered manifests.

The indentation level  for both deployment template files should be `{{- toYaml . | nindent 8 }}` rather than `{{- toYaml . | nindent 10 }}`.

https://github.com/lightdash/helm-charts/blob/78351e0c53c2adba35a49e30fc6435965a4ea10a/charts/lightdash/templates/backendDeployment.yaml#L16-L23

In the example below, the `example: annotation` is rendered two spaces more than it should be for it to be valid.

```yaml
# lightdash-values.yaml
podAnnotations:
  example: annotation
```

```yaml
# Rendered deployment manifests
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lightdash
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: backend
  template:
    metadata:
      annotations:
          example: annotation
        checksum/config: bfa55436390a23a319e9928c015e706e6b1c8af51bce87cbb9174ba9140289de
        checksum/secrets: c5cb67aae841f8ab85110e9a5f0f47de2755c4f2da347ea11105680d6b1ce9db
# ...
```

To replicate, use `helm template lightdash/lightdash -f config/lightdash-values.yaml --debug`
